apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
  name: web # Название Pod
  labels: # Метки в формате key: value
    app: web
spec: # Описание Pod
  containers: # Описание контейнеров внутри Pod
    - name: web # Название контейнера
      image: egorelik/gene_hw1_nginx:1.0 # Образ из которого создается контейнер
      volumeMounts:
        - name: app
          mountPath: /var/www/html
  initContainers:
    - name: init-hw1
      image: busybox:1.31.0
      volumeMounts:
        - name: app
          mountPath: /app
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
  volumes:
    - name: app
      emptyDir: {}    